### ISSUE TITLE
allow configuring raven version

### ISSUE THREAD

**Issue by jrencz** [segment-integrations/analytics.js-integration-sentry#17]
Right now raven is hard-coded (currently 3.5.0, latest right now is 3.7.0)

It would be better if raven version might have been passed in the segment config (where, with a little bit of effort it can be automatically placed right from `package.json` or `bower.json`)

**Comment by f2prateek** [comment]
I don't think there's significant value in supporting the overhead of managing against multiple minor releases - we should simply update to the latest.

**Comment by jrencz** [comment]
Sometimes bugs are introduced in new releases. But getting the latest is better than some older one. But sentry cdn does not support semver.

**Comment by cagdastulek** [comment]
+1 Right now Sentry.io warns for using the old version. It would be great if this is configurable.

**Comment by mshwery** [comment]
Yeah, as of today, Raven.js is at version `3.11.0` and we are still loading `3.8.0` via Segment. Several bug fixes and features have been rolled out between those versions.

**Comment by hankim813** [comment]
Hey everyone -- sorry that we haven't been best at keeping up to date with partner release logs. We're trying to have a better story around this. Not sure solving this via offloading the responsibility to customers doesn't sound like the best we can do.

We are getting to a point where we will be able to set up some internal feed for new release logs from our partners. But fwiw, the integration is using `3.12`

**Comment by danieleleoni** [comment]
Hi guys, any idea why I'm getting 1.1.6 ?

Just using `window.analytics.initialize({'Sentry': {config: "MY_CONFIG_ID" }})` from Chrome Console. I use analytics.js from npmjs `"analytics.js": "^2.9.1",` ?
@hankim813 

Could this piece of code be interesting for my problem?
https://github.com/segmentio/analytics.js/blob/12a1fd045ffd7652dad8aaf15391905666bbb5b0/component.json#L87

**Comment by hankim813** [comment]
@danieleleoni that is the open source version of the hosted ajs we serve if you use segment's default implementation (snippet/cdn). If you look https://github.com/segmentio/analytics.js-private/blob/master/package.json#L119 we are pegging the latest sentry integration version.

if you are using the open source version you want to manually bump your integration versions (a downside of using open source vs segment-hosted ajs)

**Comment by danieleleoni** [comment]
I cannot see that repo, but I understand the problem. How do we manually bump the integrations?

**Comment by hankim813** [comment]
you should be able to just bump the component.json as you linked

**Comment by danieleleoni** [comment]
The problem is that it does not build anymore...

**Comment by danieleleoni** [comment]
any news about broken build?
