### ISSUE TITLE
Add environment Optional Setting

### ISSUE THREAD

**Issue by diegoprd** [segment-integrations/analytics.js-integration-sentry#28]
Sentry supports a custom option to set your environment but segment integration doesnt: https://docs.sentry.io/clients/javascript/config/#optional-settings

This particular custom option allows you to handle different environments without the need of creating different projects for each of them in Sentry.

Add another option called `environment` to the Sentry destination setup modal under the `Optional Settings` (string value - defaulting to null) to be sent to Sentry as follows:

```
environment
Track the environment name inside Sentry.

{
  environment: 'production'
}
```

**Comment by maggieychu** [comment]
Hey @diegoprd, thanks for creating this issue! I've added this in a report to our engineers as it's a better workflow to track user requests for integration changes. That being said I'll close out this issue and update you when our team has investigated the new Sentry library.

Please submit all future requests to us here: https://segment.com/contact 

Thank you!

**Comment by GerjoGreenwaldMM** [comment]
I was looking for the same option but eventually I created a small workaround. Load this after segment initialization:

`window.analytics.ready(() => {
    if (window.Raven) window.Raven.setTagsContext({ environment: 'production' });
});`
